_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

max_epochs: -1

accelerator: gpu
devices: [0]

# FP32 precision (FP16 can be slower on V100/T4 due to cast overhead)
precision: 32-true

# perform a validation loop every N training epochs
check_val_every_n_epoch: 5

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

gradient_clip_val: 5.0
