
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

create-package: ## Create wheel and tar gz
	rm -rf dist/
	uv build

lint: ## Run ruff linter
	uv run ruff check .

lint-fix: ## Run ruff linter with auto-fix
	uv run ruff check --fix .

format: ## Run ruff formatter
	uv run ruff format .

format-check: ## Check formatting without changes
	uv run ruff format --check .

pre-commit: ## Run all pre-commit hooks
	uv run pre-commit run -a

sync: ## Sync project dependencies
	uv sync --all-groups

sync-prod: ## Sync production dependencies only
	uv sync --no-dev

lock: ## Update the lockfile
	uv lock

git-sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	uv run pytest -k "not slow"

test-full: ## Run all tests
	uv run pytest

train-ljspeech: ## Train the model
	uv run python matcha/train.py experiment=ljspeech

train-ljspeech-min: ## Train the model with minimum memory
	uv run python matcha/train.py experiment=ljspeech_min_memory

start_app: ## Start the app
	uv run python matcha/app.py
